### ISSUE TITLE
开源系统


### ISSUE THREAD

**Issue by krito111** [rymcu/RYCOM#2]

**Comment by lisifan326** [comment]
你好，我在这个软件在使用过程中发现，这个软件不能发送一些命令，如图
![BUG截图](https://github.com/rymcu/RYCOM/assets/124698046/a662baa9-7660-4257-94d4-e3cd650fcfe7)
其他软件可以发送命令并收到回复，这个软件没有收到回复

**Comment by Hugh-rymcu** [comment]
你好，时发送0x00错误问题，V2.0修复了。
